// Fill out your copyright notice in the Description page of Project Settings.


#include "VRPawn.h"

#include "Engine/World.h"
#include "EngineUtils.h"

#include "Kismet/GameplayStatics.h"

#include "Saving/PainterSaveGame.h"

#include "UI/PaintingPicker/PaintingPicker.h"

#include "PaintingGameMode.h"

AVRPawn::AVRPawn()
{
	PrimaryActorTick.bCanEverTick = false;

	VRRoot = CreateDefaultSubobject<USceneComponent>(TEXT("VRRoot"));
	SetRootComponent(VRRoot);

	Camera = CreateDefaultSubobject<UCameraComponent>(TEXT("Camera"));
	Camera->SetupAttachment(VRRoot);
}

void AVRPawn::BeginPlay()
{
	Super::BeginPlay();

	if (RightHandControllerClass)
	{
		RightHandController = GetWorld()->SpawnActor<AHandControllerBase>(RightHandControllerClass);
		RightHandController->AttachToComponent(GetRootComponent(), FAttachmentTransformRules::SnapToTargetIncludingScale);
		RightHandController->SetHand(EControllerHand::Right);
		RightHandController->SetOwner(this);

	}

	if (LeftHandControllerClass)
	{
		LeftHandController = GetWorld()->SpawnActor<AHandControllerBase>(LeftHandControllerClass);
		LeftHandController->AttachToComponent(GetRootComponent(), FAttachmentTransformRules::SnapToTargetIncludingScale);
		LeftHandController->SetHand(EControllerHand::Left);
		LeftHandController->SetOwner(this);
	}
}

void AVRPawn::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent)
{
	Super::SetupPlayerInputComponent(PlayerInputComponent);

	PlayerInputComponent->BindAction(TEXT("RightTrigger"), EInputEvent::IE_Pressed, this, &AVRPawn::RightTriggerPressed);
	PlayerInputComponent->BindAction(TEXT("RightTrigger"), EInputEvent::IE_Released, this, &AVRPawn::RightTriggerRealeased);

	PlayerInputComponent->BindAction(TEXT("PageRight"), EInputEvent::IE_Pressed, this, &AVRPawn::PaginateRightAxisInput);

	PlayerInputComponent->BindAction(TEXT("PageLeft"), EInputEvent::IE_Pressed, this, &AVRPawn::PaginateLeftAxisInput);


	//PlayerInputComponent->BindAxis(TEXT("PaginateRight"), this, &AVRPawn::PaginateRightAxisInput);

}

void AVRPawn::PaginateRightAxisInput()
{
	UE_LOG(LogTemp, Warning, TEXT("Right Page"));
	/*int32 PaginationOffset = 0;
	PaginationOffset += AxisValue > PaginationThumbstickThreshold ? 1 : 0;
	PaginationOffset += AxisValue < -PaginationThumbstickThreshold ? -1 : 0;

	if (PaginationOffset != LastPaginationOffset && PaginationOffset != 0)
	{
		UpdateCurrentPage(PaginationOffset);
	}

	LastPaginationOffset = PaginationOffset;*/
	UE_LOG(LogTemp, Warning, TEXT("LastPaginationOffset %d "), LastPaginationOffset);


	//PaginationOffset = 0;
	UE_LOG(LogTemp, Warning, TEXT("PaginationOffset initialised %d "), PaginationOffset);

	PaginationOffset += 1;
	UE_LOG(LogTemp, Warning, TEXT("PaginationOffset after +1 %d "), PaginationOffset);

	if (PaginationOffset != LastPaginationOffset && PaginationOffset != 0)
	{
		UE_LOG(LogTemp, Warning, TEXT("PaginationOffset in loop %d "), PaginationOffset);
		UpdateCurrentPage(PaginationOffset);
	}
	UE_LOG(LogTemp, Warning, TEXT("PaginationOffset after loop %d "), PaginationOffset);

	LastPaginationOffset = PaginationOffset; 

}

void AVRPawn::PaginateLeftAxisInput()
{
	UE_LOG(LogTemp, Warning, TEXT("Left Page"));
}

void AVRPawn::UpdateCurrentPage(int32 Offset)
{
	for (TActorIterator<APaintingPicker> PaintingPickerItr(GetWorld()); PaintingPickerItr; ++PaintingPickerItr)
	{
		PaintingPickerItr->UpdateCurrentPage(Offset);
	}
}

